Timakinの原稿
golangtokyo/gopherwalker pull request #1
Opened 2017-10-16 13:45 UTC by timakin

Markdownが処理できてないですが、一応原稿はできてます！

2017-10-16 13:55 UTC, tenntenn requested changes

2017-10-16 13:55 UTC, tenntenn commented on articles/config.yml
> +edt: ["tenntenn", "timakin"]
ここは編集者ですねー。もちろん、編集やってくれても大丈夫です！

2017-10-16 13:55 UTC, tenntenn commented on articles/timakin.re
> +認証処理というのは往々にして実装が複雑になりがちです。初回リクエスト時に認証処理として具体的にやるべきことは、たとえば以下のようなことです。
本なので、`以下`という概念はない。

2017-10-16 13:55 UTC, tenntenn commented on articles/timakin.re
> +```
```
//list[timakin_list1]{
ここにコード
//}
```

2017-10-16 13:55 UTC, tenntenn commented on articles/timakin.re
> +起動スクリプトは以下のような書き方になると思います。
`起動スクリプトは@<list>{timakin_list1}のような書き方になると思います。`

2017-10-16 13:55 UTC, tenntenn commented on articles/timakin.re
> +という点でしょうか。1つ目はルーティングの定義を外部の関数に切り出しておくというだけなのですが、見栄えが良いので個人的にオススメです。
`1つ目` -> `ひとつめ`

2017-10-16 13:55 UTC, tenntenn commented on articles/timakin.re
> +2点目は、Goのリクエストハンドラの実装方法です。この点は次の節で詳しく解説いたします。
`2つ目` -> `ふたつめ`

2017-10-16 13:55 UTC, tenntenn commented on articles/timakin.re
> +
空行いらない

2017-10-16 13:55 UTC, tenntenn commented on articles/timakin.re
> +それはあまりよろしくないので、GoのInterfaceを使って、それらのミドルウェアのオブジェクトをDependency(依存オブジェクト)として持ったハンドラを作成すると便利です。
`Interface` -> `インタフェース`

2017-10-16 13:55 UTC, tenntenn commented on articles/timakin.re
> +CustomHandlerがその実装例になります。このstructはServeHTTPメソッドを実装しています。これを実装すればGoはHTTPリクエストハンドラとしてみなしてくれます。
`struct` -> `構造体`

2017-10-16 13:55 UTC, tenntenn commented on articles/timakin.re
> +今回の認証処理で使うのは、認証情報へのデータアクセスクライアントなどを持ったRepositoryオブジェクト、をさらに内部に持ったビジネスロジックを実装したService構造体、を持ったDependencyという、ちょっと入れ子構造として多層なオブジェクトを持ったハンドラです。
`今回の認証処理で使うのは` ->  `ここでは...を認証処理に使います`

2017-10-16 13:55 UTC, tenntenn commented on articles/timakin.re
> +今回の認証処理で使うのは、認証情報へのデータアクセスクライアントなどを持ったRepositoryオブジェクト、をさらに内部に持ったビジネスロジックを実装したService構造体、を持ったDependencyという、ちょっと入れ子構造として多層なオブジェクトを持ったハンドラです。
`Repository` -> `@<code>{Repository}`
あと同じく

2017-10-16 14:05 UTC, tenntenn commented on articles/timakin.re
> +== まとめ
`はじめに` の対は `おわりに`

2017-10-16 14:19 UTC, timakin commented on articles/config.yml
> +edt: ["tenntenn", "timakin"]
へ...編集とは一体...書くことではなくレビューする的なあれですかね

2017-10-16 14:33 UTC, timakin commented
@tenntenn もろもろ直しました！

2017-10-16 16:59 UTC, pospome commented on articles/config.yml
> +edt: ["tenntenn", "timakin"]
>へ...編集とは一体...

w

2017-10-17 08:20 UTC, tenntenn commented on articles/config.yml
> +edt: ["tenntenn", "timakin"]
漫画家と編集者の関係と同じです。

2017-10-17 08:48 UTC, tenntenn requested changes

2017-10-17 08:48 UTC, tenntenn commented on articles/timakin.re
> +初めまして、株式会社Gunosyの新規事業開発室でエンジニアをしております、timakinです。Gunosyでは主にGoのAPIとSwiftのiOSクライアントサイド開発を担当しております。
`初めまして`
はじめましてじゃないかもしれない。

2017-10-17 08:48 UTC, tenntenn commented on articles/timakin.re
> +初めまして、株式会社Gunosyの新規事業開発室でエンジニアをしております、timakinです。Gunosyでは主にGoのAPIとSwiftのiOSクライアントサイド開発を担当しております。
`しております`が続いている。

2017-10-17 08:48 UTC, tenntenn commented on articles/timakin.re
> +弊社のプロダクトもそうですが、モバイルアプリでは起動直後に一見特段の認証処理をせずにコンテンツを表示します。
`弊社` -> `Gunosy`

```
弊社のプロダクトもそうですが、モバイルアプリでは起動直後に一見特段の認証処理をせずにコンテンツを表示します。
```

だと分かるけど、分からないので、

```
起動直後に特にユーザの認証を必要としないモバイルアプリは多く存在しています。
しかし、裏側ではデバイス認証をしておき、正確にユーザ情報を管理しなくてはならない場合があります。

本章では、モバイルファーストなプロダクトにおいて、このような認証処理をGoで実装する方法について、Gunosyの実例を踏まえて解説します。
```

とかの方がいいのでは？

2017-10-17 08:48 UTC, tenntenn commented on articles/timakin.re
> +== main.go
目次になるので、見出しだけおって分かるレベルにする。

2017-10-17 08:48 UTC, tenntenn commented on articles/timakin.re
> +	_ "google.golang.org/appengine/remote_api"
sortされてない？

2017-10-17 08:48 UTC, tenntenn commented on articles/timakin.re
> +	// Routing
和書はコメントは日本語で書いた方がいいでしょう。

2017-10-17 08:48 UTC, tenntenn commented on articles/timakin.re
> +appengine特有のpackageが一部読み込まれていますが、基本的な書き方は変わりません。
`Google App Engine`

2017-10-17 08:48 UTC, tenntenn commented on articles/timakin.re
> + * 認証処理をauthというpackageにまとめている
`auth` -> `@<code>{auth}`

Goの機能としての名称の `パッケージ` の場合は、英語にせず、カタカナの方がよいです。
英語にしちゃうと、コードと見分けがつかない。

2017-10-17 08:48 UTC, tenntenn commented on articles/timakin.re
> +さらに、Goのcontextという概念がよく実装で問題になります。これはGoのchannel間でキャンセル処理を統一管理する用途、そしてリクエストに限定的な値(ユーザー情報など)をストアするための用途で使われる機構です。
チャネル間ではなくゴールーチン間では？

2017-10-17 08:48 UTC, tenntenn commented on articles/timakin.re
> +
細く空行をあけない。
段落が分かれてしまいます。
意味の変わる単位で空行を入れましょう。

2017-10-17 08:48 UTC, tenntenn commented on articles/timakin.re
> +今回はPOSTリクエストとの/initというエンドポイントを、初期の認証処理の入り口としておいて見ます。
`@<code>{/api/init}`

2017-10-17 08:48 UTC, tenntenn commented on articles/timakin.re
> +今回はPOSTリクエストとの/initというエンドポイントを、初期の認証処理の入り口としておいて見ます。
`おいて見ます` -> `置いてみます`

2017-10-17 08:48 UTC, tenntenn commented on articles/timakin.re
> +//list[routing.go][ルーティング]{
何の？リスト名だけ見て分かるように。

2017-10-17 08:48 UTC, tenntenn commented on articles/timakin.re
> +	DUID       string `json:"duid" validate:"required"`
`validate`タグも揃えた方が分かりやすいかもしれません。

2017-10-17 08:48 UTC, tenntenn commented on articles/timakin.re
> +受け取ったInit用のリクエストbodyをパースして、ビジネスロジックへの流し込みます。そして結果をレスポンスpayloadに詰めて返却する、というのがおおまかな流れです。
`初期化用のリクエストボディ`

2017-10-17 08:48 UTC, tenntenn commented on articles/timakin.re
> + * DUID - デバイスのユニークID
表を使いましょう。

2017-10-17 13:46 UTC, timakin commented on articles/timakin.re
> +
ここは書き出しとしてあけましたが、これ以外のところもろもろ詰めておきました！

2017-10-17 14:51 UTC, tenntenn requested changes

2017-10-17 14:51 UTC, tenntenn commented on articles/timakin.re
> +今回はプロダクトのフェーズがその段階に達する前の、シンプルなデバイス認証をどうやってGoで実装すべきかについて書いていきます。
今回

2017-10-17 14:51 UTC, tenntenn commented on articles/timakin.re
> +起動スクリプトは@<list>{main.go}のような書き方になります。
main.goだと、衝突の恐れがあるので、プリフィクスが欲しいです

2017-10-17 14:51 UTC, tenntenn commented on articles/timakin.re
> +Google App Engine特有のpackageが一部読み込まれていますが、基本的な書き方は変わりません。
パッケージ

2017-10-17 14:51 UTC, tenntenn commented on articles/timakin.re
> +//list[custom.go][カスタムハンドラの定義]{
プリフィクス

2017-10-17 14:51 UTC, tenntenn commented on articles/timakin.re
> +特に気にせず書いてしまうと、パッケージのグローバル変数として定義したオブジェクトを使ったり、リクエストごとにLoggerを初期化、などとなります。
ロガーを初期化したり

2017-10-17 14:51 UTC, tenntenn commented on articles/timakin.re
> +それはあまりよろしくないので、Goのインタフェースを使って、それらのミドルウェアのオブジェクトを@<code>{Dependency}(依存オブジェクト)として持ったハンドラを作成すると便利です。
指示代名詞が多いので、別の表現にすると良いです

2017-10-17 14:51 UTC, tenntenn commented on articles/timakin.re
> +まさにこのような用途で@<code>{context}を使います。例えばDBクライアントに実行メソッドとして@<code>{Exec}というのが用意されていれば、標準パッケージならほぼ確実に@<code>{ExecContext}というような、第一引数にcontextを渡せるメソッドが生えています。
コンテキストはコードではなく、用語なのでカタカナで良いのでは？

2017-10-17 14:51 UTC, tenntenn commented on articles/timakin.re
> +今回はPOSTリクエストとの@<code>{/api/init}というエンドポイントを、初期の認証処理の入り口として置いてみます。
今回

2017-10-17 14:51 UTC, tenntenn commented on articles/timakin.re
> +今回はPOSTリクエストとの@<code>{/api/init}というエンドポイントを、初期の認証処理の入り口として置いてみます。
置いています

2017-10-17 14:51 UTC, tenntenn commented on articles/timakin.re
> +冒頭でルーティング定義を別メソッドに切り出して置くと見栄えが良い的な話をしましたが、ここがその実装です。
話をする → 述べる

2017-10-19 04:11 UTC, tenntenn requested changes

2017-10-19 04:11 UTC, tenntenn commented on articles/timakin.re
> +株式会社Gunosy新規事業開発室エンジニアのtimakinです。Gunosyでは主にGoのAPIとSwiftのiOSクライアントサイド開発を担当しております。
Twitterのアカウントをfootnoteいれてもいいかも。

```
株式会社Gunosy新規事業開発室エンジニアのtimakin@<fn>{timakin_fn1}です。Gunosyでは主にGoのAPIとSwiftのiOSクライアントサイド開発を担当しております。

//footnote[timakin_fn1][https://twitter.com/__timakin__]
```

2017-10-19 04:11 UTC, tenntenn commented on articles/timakin.re
> +@<code>{Init}という必要の関数の中で@<code>{User}, @<code>{Device}, @<code>{DeviceApp}を登録していきます。今回はGoogle Cloud PlatformのDatastoreをデータベースとして利用しているので、@<code>{RunInTransaction}という関数でトランザクションを張っています。
カンマが半角になってる

2017-10-21 03:36 UTC, tenntenn approved these changes

2017-10-21 03:37 UTC, merged