そなたの原稿
golangtokyo/gopherwalker pull request #2
Opened 2017-10-18 01:16 UTC by sonatard

@tenntenn レビューお願いいたします！

2017-10-18 01:25 UTC, timakin commented on articles/contributors.re
> +ピックアップ株式会社所属。新規事業のサーバサイドエンジア。golang.tokyoの運営に参加。新卒で入社したメーカーでC言語によるTCP/IPプロトコルスタックを開発。ghqにSubversion対応のPull Requestを送りGoデビュー。C言語プログラマから脱出する道をGoに見出し今に至る。
エンジニア

2017-10-18 01:26 UTC, timakin commented on articles/sonatard.re
> +	* GoでProtocol Buffersの採用は容易である
ここってこんなあける必要ありましたっけ。表示問題なければいいかな感ありますが

2017-10-18 01:27 UTC, tenntenn requested changes

2017-10-18 01:27 UTC, tenntenn commented on articles/sonatard.re
> +今回はその中でもクライアントとサーバ間でやりとりする構造化データ仕様のProtocol Buffersと周辺技術について紹介します。
今回は→本章では

2017-10-18 01:27 UTC, tenntenn commented on articles/sonatard.re
> +	* GoでProtocol Buffersの採用は容易である
スペースこんなにあけてもちゃんとパースされました？

2017-10-18 01:27 UTC, tenntenn commented on articles/sonatard.re
> +生成された person.pb.go を利用してコードを書きます。
英字との間はスペースいらない。勝手にTexがやります

2017-10-18 01:27 UTC, tenntenn commented on articles/sonatard.re
> +time.TimeはProtocol Buffersの標準で規定されていないためgoogleが作成した google/protobuf/timestamp.proto のインポートが必要になります。
googleが開発した
→Googleが開発した

2017-10-18 01:27 UTC, tenntenn commented on articles/sonatard.re
> +現在時刻の取得をする func TimestampNow() *tspb.Timestamp 、Goの time.Time から Timestamp に変換する func TimestampProto(t time.Time) (*tspb.Timestamp, error) などがあります。
コード類は `@<code>{}`で括ると良いでしょう

2017-10-18 01:27 UTC, tenntenn commented on articles/sonatard.re
> +この章では、Protocol Buffersと比較対象となる技術スタックを紹介します。
この章
か
本章は統一

2017-10-18 01:27 UTC, tenntenn commented on articles/sonatard.re
> +== TIPS
`==column TIPS` というコラムを書く記法もあります

2017-10-18 01:29 UTC, timakin commented on articles/sonatard.re
> +今回はその中でもクライアントとサーバ間でやりとりする構造化データ仕様のProtocol Buffersと周辺技術について紹介します。
今回 -> ここでは（と、tenntennさんが言っていました）

2017-10-18 01:29 UTC, timakin commented on articles/sonatard.re
> +もし間違った実装をしても実際にリクエストを送信して結果を確認しないことは検証することができません。
確認しないことは -> しないことには

2017-10-18 01:30 UTC, timakin commented on articles/sonatard.re
> +バイナリフォーマットであるためJSONのようにそのままHTTPリクエストのBodyに乗せて送信することができません。
Body -> ボディ

2017-10-18 01:30 UTC, timakin commented on articles/sonatard.re
> +公式のprotocコマンドだけではすべての言語に対応していないため3rd party製のツールをインストールする必要があります。
サードパーティ

2017-10-18 01:30 UTC, timakin commented on articles/sonatard.re
> +公式のprotocコマンドだけではすべての言語に対応していないため3rd party製のツールをインストールする必要があります。
@<code>{protoc}

2017-10-18 01:31 UTC, timakin commented on articles/sonatard.re
> +テキストフォーマットのXMLやJSONより小さく、速く、そしてシンプルです。.protoファイルにデータを構造化する方法を定義してから、
.protoって@<code>{.proto}で囲うか迷いますねw

2017-10-18 01:31 UTC, timakin commented on articles/sonatard.re
> +サーバでHTTPヘッダのContent-TypeからJSONかProtocol Buffersかを判断してデコードするようしておくと開発時のストレスがなくなります。
@<code>{Content-TYpe}

2017-10-18 01:32 UTC, timakin commented on articles/sonatard.re
> +gRPCを利用していればgrpc-gatewayを使う解決策もあります。
これもgrpc-gatewayは@<code>{}なんですかねえ。

2017-10-18 01:32 UTC, timakin commented on articles/sonatard.re
> +生成された person.pb.go を利用してコードを書きます。
@<code>{person.pb.go}

2017-10-18 01:32 UTC, timakin commented on articles/sonatard.re
> +//list[directory][ディレクトリ構成]{
これせっかくなのでどっかで参照したほうがいいかもですね

2017-10-18 01:33 UTC, timakin commented on articles/sonatard.re
> +//list[proto_main.go][生成されたperson.Person構造体の利用]{
これも参照したほうが？連続してるので無理にする必要ないですが。

2017-10-18 01:33 UTC, timakin commented on articles/sonatard.re
> +float64				double
インデント揃ってない説？表示問題なければ大丈夫です

2017-10-18 01:34 UTC, timakin commented on articles/sonatard.re
> +time.TimeはProtocol Buffersの標準で規定されていないためgoogleが作成した google/protobuf/timestamp.proto のインポートが必要になります。
@<code>{time.Time}

2017-10-18 01:34 UTC, timakin commented on articles/sonatard.re
> +time.TimeはProtocol Buffersの標準で規定されていないためgoogleが作成した google/protobuf/timestamp.proto のインポートが必要になります。
@<code>{google/protobuf/timestamp.proto}

2017-10-18 01:34 UTC, timakin commented on articles/sonatard.re
> +また github.com/golang/protobuf/ptypes にTimestampに関連する関数が用意されています。
code

2017-10-18 01:34 UTC, timakin commented on articles/sonatard.re
> +また github.com/golang/protobuf/ptypes にTimestampに関連する関数が用意されています。
TimeStamp -> タイムスタンプ

2017-10-18 01:34 UTC, timakin commented on articles/sonatard.re
> +現在時刻の取得をする func TimestampNow() *tspb.Timestamp 、Goの time.Time から Timestamp に変換する func TimestampProto(t time.Time) (*tspb.Timestamp, error) などがあります。
codeでいっぱい囲めそう

2017-10-18 01:35 UTC, timakin commented on articles/sonatard.re
> +その場合にはJSON-RPCのJSON部分をProtocol Buffersに置き換えますが、RPCのAPI実行ルール部はそのまま利用することになります。つまりHTTP+JSON-RPCのRPC部+Protocol Buffersという構成になります。
実行ルール部 -> 実行ルール部分

2017-10-18 01:36 UTC, timakin commented on articles/sonatard.re
> +== TIPS
Tips? Appendix? 普通の本だと冊子の最後にAppendixだし、Tipsでいいんですかね。

2017-10-18 01:37 UTC, timakin commented on articles/sonatard.re
> +== TIPS
お〜

2017-10-18 01:50 UTC, sonatard commented on articles/sonatard.re
> +	* GoでProtocol Buffersの採用は容易である
タブであけてしまいました　スペースにしておきます

2017-10-18 01:51 UTC, sonatard commented on articles/sonatard.re
> +テキストフォーマットのXMLやJSONより小さく、速く、そしてシンプルです。.protoファイルにデータを構造化する方法を定義してから、
ドットはずしてprotoファイルにして囲わないにしてみます

2017-10-18 02:10 UTC, sonatard commented on articles/sonatard.re
> +	* GoでProtocol Buffersの採用は容易である
タブであけてしまいました　スペースにしておきます

2017-10-18 02:15 UTC, sonatard commented on articles/sonatard.re
> +float64				double
あれ？　手元もvimだと揃っているのですがタブ幅のサイズの問題かな？

2017-10-18 02:41 UTC, sonatard commented on articles/sonatard.re
> +== TIPS
コラム記法LaTeXのコンパイルでラーになってしまったので、とりあえずそのままにしています
https://github.com/kmuto/review/blob/master/doc/format.ja.md#コラムなど

2017-10-18 02:42 UTC, sonatard commented
修正doneです

2017-10-18 11:31 UTC, timakin commented on articles/sonatard.re
> +正しく比較検討するためには、同じレイヤー技術間での比較が必要です。
同じレイヤー「の」？

2017-10-18 11:32 UTC, timakin commented on articles/sonatard.re
> +比較検討の対象を誤ると「Protocol Buffersを利用するためにはgRPCを利用しなければならない」のような誤解をしてしまいます。
のような -> というような

2017-10-18 11:36 UTC, timakin commented on articles/sonatard.re
> +packageを設定すると生成されるGoのソースコードも同様のpackageになります。
package -> パッケージ

2017-10-18 11:37 UTC, timakin commented on articles/sonatard.re
> +==== protoファイルにpackageを指定した場合に、Swfitのソースコードに追加される余計なPrefixを削除する。
Swfit -> Swift

2017-10-18 11:37 UTC, timakin commented on articles/sonatard.re
> +==== protoファイルにpackageを指定した場合に、Swfitのソースコードに追加される余計なPrefixを削除する。
Prefix -> プレフィクス

2017-10-18 11:37 UTC, timakin commented on articles/sonatard.re
> +==== protoファイルにpackageを指定した場合に、Swfitのソースコードに追加される余計なPrefixを削除する。
package -> パッケージ

2017-10-19 01:33 UTC, sonatard commented on articles/sonatard.re
> +==== protoファイルにpackageを指定した場合に、Swfitのソースコードに追加される余計なPrefixを削除する。
Swfit
謎のフィットネスサービスみたいな名前になってしまいました

2017-10-21 03:34 UTC, tenntenn approved these changes

2017-10-21 03:34 UTC, tenntenn commented on articles/sonatard.re
> +ピックアップ株式会社で新規事業のサーバイサイドエンジニアをしている@sonatardです。
see: https://github.com/golangtokyo/gopherwalker/pull/1#discussion_r145596752

2017-10-21 03:34 UTC, tenntenn commented on articles/sonatard.re
> +特に4つの点をお伝えできればと思います。
いい切った方がよいでしょう

2017-10-21 03:34 UTC, merged